# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: do the npm install and build webpack
        run: |
          npm install
          npm run build

      # uploads the build for the tests
      - uses: actions/upload-artifact@master
        with:
          name: webpack artifacts
          path: public/

  test:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        # pjm - runs test on 2 environments
        os: [ubuntu-latest, windows-2016]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@master
      with:
        name: webpack artifacts
        path: public
    
#    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: do the npm install, and test
      run: |
        npm install
        npm test
      env:
        CI: true
      
#    - run: npm ci
#    - run: npm run build --if-present
#    - run: npm test
